### ISSUE TITLE
Occasional hang when calling IPMI functions

### ISSUE THREAD

**Issue by solemnwarning** [kontron/python-ipmi#169]
Hello,

I'm not sure if this is a library bug or something I'm doing wrong, but in one of my projects the IPMI library sometimes hangs within calls to `ipmi.get_chassis_status()` and `ipmi.session.establish()` in the `ipmiwake()` function [here](https://github.com/solemnwarning/powernap/blob/ced5fe170373279d5cf2d5774726f7bf8fead508/bin/powerwake#L148).

The BMC in question is on a SuperMicro server and the machine is shut down and booted on demand, which may or may not be a contributing factor to the hang (I've not been able to figure out how to trigger it - it just happens sometimes on a machine which is running this code periodically).

Any ideas, or things I can do to try narrowing the scope of the bug down?

Thanks

**Comment by canteuni** [comment]
Hello,

I'm not the maintainer of this library, just an occasional contributor, but maybe I can help you.

There is a small possibility that the BMC is "overwhelmed" and can't process your `get_chassis_status()` command if it is currently processing a "power on" command. You can try to reproduce the issue by issuing `get_chassis_status()` while spamming "power on" or "power off" commands but I'm not sure (and perhaps the server won't be happy to be turned on and off multiples times like this).

Other ideas that come to my mind to narrow the scope of the bug :
- try using interface `ipmitool` instead of native `rmcp` in your function (you will need to install `ipmitool` on your machine). If the bug disappear, maybe it's an issue with this library. If the bug is still there, maybe it's an issue with your own BMC
- try using a BMC simulator (something [like this](https://github.com/vapor-ware/ipmi-simulator)) and call your function against this simulator. If the bug disappear, maybe it's an issue with your BMC. If the bug is still there, maybe it's an issue with this library

**Comment by solemnwarning** [comment]
I'm still seeing this periodically, it appears to be hanging inside the Python logging library:

```
Traceback (most recent call last):
File "/usr/bin/powerwake", line 381, in <module>
  ipmiwake(target_config)
File "/usr/bin/powerwake", line 174, in ipmiwake
  chassis_status = ipmi.get_chassis_status()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3/dist-packages/pyipmi/chassis.py", line 31, in get_chassis_status
  return ChassisStatus(self.send_message_with_name('GetChassisStatus'))
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3/dist-packages/pyipmi/__init__.py", line 206, in send_message_with_name
  rsp = self.send_message(req)
        ^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3/dist-packages/pyipmi/__init__.py", line 190, in send_message
  rsp = self.interface.send_and_receive(req)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3/dist-packages/pyipmi/interfaces/rmcp.py", line 565, in send_and_receive
  rx_data = self._send_and_receive(target=req.target,
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3/dist-packages/pyipmi/interfaces/rmcp.py", line 534, in _send_and_receive
  received = rx_filter(header, rx_data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3/dist-packages/pyipmi/interfaces/ipmb.py", line 216, in rx_filter
  log().debug('{:s}: {:d} {:d}'.format(msg, left, right))
  ^^^^^
File "/usr/lib/python3/dist-packages/pyipmi/logger.py", line 21, in log
  return logging.getLogger('pyipmi')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/logging/__init__.py", line 2089, in getLogger
  return Logger.manager.getLogger(name)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/logging/__init__.py", line 1341, in getLogger
  _acquireLock()
File "/usr/lib/python3.11/logging/__init__.py", line 235, in _acquireLock
  _lock.acquire()
```
